# Generated by Django 4.2.6 on 2023-10-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0002_cruise_inforequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoRequest',
        ),
    ]
